[package]
name = "alexandria"
version = "0.1.0"
edition = "2024"

[[test]]
name = "compile_test"
harness = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive", "unstable-doc"] }
diagnostic = { version = "0.1.0", path = "../diagnostic" }
lexer = { version = "0.1.0", path = "../lexer" }
nameres = { version = "0.1.0", path = "../nameres" }
parser = { version = "0.1.0", path = "../parser" }
source = { version = "0.1.0", path = "../source" }

[dev-dependencies]
datatest-stable = "0.3.3"
